[metadata]
name = pydbg
author = 5pyd3r
author_email = 5pyd3r.tarsylia@gmail.com
summary = Python binary debugger
license = MIT
home_page = https://github.com/5pyd3r/pydbg
classifier =
    Development Status :: 1 - Planning
    Environment :: Console
    Intended Audience :: Developers
    Operating System :: Windows
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Software Development :: Debuggers

[files]

[build-system]
requires = ["setuptools", "wheel", "Cython"]

[build_ext]
inplace=1

[sdist_wheel]
inplace=1